version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - nosql-data:/data/db
    ports:
      - 26000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  mariadb:
    image: mariadb
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  node:
    image: node:current-alpine
    links:
      - mongo
      - mariadb
    depends_on:
      - mongo
      - mariadb
    volumes:
      - ./:/data/app
    working_dir: /data/app
    command: "npm start"

  importer:
    image: node:current-alpine
    links:
      - mongo
      - mariadb
    depends_on:
      - mongo
      - mariadb
    volumes:
      - ./:/data/app
    working_dir: /data/app
    command: "npm run import"


volumes:
  nosql-data: {}
  sql-data: {}
